//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.1.4.0 (Newtonsoft.Json v12.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Properties;
using Elements.Validators;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace Elements
{
    #pragma warning disable // Disable all warnings

    /// <summary>A subsection of a slab</summary>
    [Newtonsoft.Json.JsonConverter(typeof(Elements.Serialization.JSON.JsonInheritanceConverter), "discriminator")]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.4.0 (Newtonsoft.Json v12.0.0.0)")]
    [UserElement]
	public partial class SlabSubdivision : GeometricElement
    {
        [Newtonsoft.Json.JsonConstructor]
        public SlabSubdivision(string @identifier, Profile @profile, double @depth, double @volume, Transform @transform, Material @material, Representation @representation, System.Guid @id, string @name)
            : base(transform, material, representation, id, name)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<SlabSubdivision>();
            if(validator != null)
            {
                validator.Validate(new object[]{ @identifier, @profile, @depth, @volume, @transform, @material, @representation, @id, @name});
            }
        
            this.Identifier = @identifier;
            this.Profile = @profile;
            this.Depth = @depth;
            this.Volume = @volume;
        }
    
        /// <summary>The identifier of this section.</summary>
        [Newtonsoft.Json.JsonProperty("Identifier", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Identifier { get; set; }
    
        /// <summary>The id of the profile to extrude.</summary>
        [Newtonsoft.Json.JsonProperty("Profile", Required = Newtonsoft.Json.Required.AllowNull)]
        public Profile Profile { get; set; }
    
        /// <summary>The depth of the slab.</summary>
        [Newtonsoft.Json.JsonProperty("Depth", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
        public double Depth { get; set; }
    
        /// <summary>The volume of the slab section.</summary>
        [Newtonsoft.Json.JsonProperty("Volume", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
        public double Volume { get; set; }
    
    
    }
}